#

# DO NOT EDIT THIS FILE - THIS DOCUMENTATION WAS CREATED BY A SCRIPT - see EJAM/data-raw/datacreate_testinput_shapes_2.R or similar files

#' @name testinput_shapes_2
#' @docType data
#' @title testinput_shapes_2 dataset
#' @description Sample shapefile/polygon data as spatial data.frame
#' @seealso same as [testshapes_2]
'testinput_shapes_2'