#

# DO NOT EDIT THIS FILE - THIS DOCUMENTATION WAS CREATED BY A SCRIPT - see EJAM/data-raw/datacreate_testoutput_ejamit_fips_cities.R or similar files

#' @name testoutput_ejamit_fips_cities
#' @docType data
#' @title testoutput_ejamit_fips_cities dataset
#' @description This is the output of ejamit(fips = testinput_fips_cities)
#' @seealso [ejamit()] [testdata()]
'testoutput_ejamit_fips_cities'