# 

# DO NOT EDIT THIS FILE - THIS DOCUMENTATION WAS CREATED BY A SCRIPT - see EJAM/data-raw/datacreate_testinput_mact.R or similar files

#' @name testinput_mact
#' @docType data
#' @title testinput_mact dataset
#' @description MACT subpart code as example of input, e.g., latlon_from_mactsubpart(testinput_mact)
'testinput_mact'
