#

# DO NOT EDIT THIS FILE - THIS DOCUMENTATION WAS CREATED BY A SCRIPT - see EJAM/data-raw/datacreate_testoutput_ejamit_fips_counties.R or similar files

#' @name testoutput_ejamit_fips_counties
#' @docType data
#' @title testoutput_ejamit_fips_counties dataset
#' @description This is the output of ejamit(fips = testinput_fips_counties)
#' @seealso [ejamit()] [testdata()]
'testoutput_ejamit_fips_counties'