#

# DO NOT EDIT THIS FILE - THIS DOCUMENTATION WAS CREATED BY A SCRIPT - see EJAM/data-raw/datacreate_testinput_address_table.R or similar files

#' @name testinput_address_table
#' @docType data
#' @title datasets for trying address-related functions
#' @description datasets for trying address-related functions (testinput_address_parts, testinput_address_2, testinput_address_9, testinput_address_table_9, testinput_address_table, testinput_address_table_goodnames, testinput_address_table_withfull)
#' @aliases testinput_address_parts testinput_address_2 testinput_address_9 testinput_address_table_9 testinput_address_table testinput_address_table_goodnames testinput_address_table_withfull
'testinput_address_table'