#

# DO NOT EDIT THIS FILE - THIS DOCUMENTATION WAS CREATED BY A SCRIPT - see EJAM/data-raw/datacreate_testoutput_ejamit_shapes_2.R or similar files

#' @name testoutput_ejamit_shapes_2
#' @docType data
#' @title testoutput_ejamit_shapes_2 dataset
#' @description This is the output of ejamit(shapefile = testinput_shapes_2, radius = 0)
#' @seealso [ejamit()] [testdata()]
'testoutput_ejamit_shapes_2'