# 

# DO NOT EDIT THIS FILE - THIS DOCUMENTATION WAS CREATED BY A SCRIPT - see EJAM/data-raw/datacreate_testinput_program_name.R or similar files

#' @name testinput_program_name
#' @docType data
#' @title testinput_program_name dataset
#' @description EPA program name codes vector as example of input, e.g., latlon_from_program(testinput_program_name)
'testinput_program_name'
