# 

# DO NOT EDIT THIS FILE - THIS DOCUMENTATION WAS CREATED BY A SCRIPT - see EJAM/data-raw/datacreate_testinput_sic.R or similar files

#' @name testinput_sic
#' @docType data
#' @title testinput_sic dataset
#' @description SIC codes vector as example of input to e.g., latlon_from_sic(testinput_sic)
'testinput_sic'
