# 

# DO NOT EDIT THIS FILE - THIS DOCUMENTATION WAS CREATED BY A SCRIPT - see EJAM/data-raw/datacreate_testinput_naics.R or similar files

#' @name testinput_naics
#' @docType data
#' @title testinput_naics dataset
#' @description NAICS codes vector as example of input, e.g., latlon_from_naics(testinput_naics)
'testinput_naics'
