# 

# DO NOT EDIT THIS FILE - THIS DOCUMENTATION WAS CREATED BY A SCRIPT - see EJAM/data-raw/datacreate_testinput_fips_cities.R or similar files

#' @name testinput_fips_cities
#' @docType data
#' @title testinput_fips_cities dataset
#' @description Census FIPS codes vector as example of input, e.g., ejamit(fips = testinput_fips_cities)
'testinput_fips_cities'
